# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  HEngine_config = debug
  Test_config = debug
endif
ifeq ($(config),release)
  HEngine_config = release
  Test_config = release
endif

PROJECTS := HEngine Test

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

HEngine:
ifneq (,$(HEngine_config))
	@echo "==== Building HEngine ($(HEngine_config)) ===="
	@${MAKE} --no-print-directory -C HEngine -f Makefile config=$(HEngine_config)
endif

Test: HEngine
ifneq (,$(Test_config))
	@echo "==== Building Test ($(Test_config)) ===="
	@${MAKE} --no-print-directory -C Test -f Makefile config=$(Test_config)
endif

clean:
	@${MAKE} --no-print-directory -C HEngine -f Makefile clean
	@${MAKE} --no-print-directory -C Test -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   HEngine"
	@echo "   Test"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"